### ISSUE TITLE
search any keywords always return 'not found'

### ISSUE THREAD

**Issue by s0urcelab** [libredmm/opendmm#4]
![image](https://user-images.githubusercontent.com/13177782/59707621-91e2e980-9235-11e9-802b-15be296993ea.png)

**Comment by junzh0u** [comment]
Is it "any" keywords or just "some" keywords? Have you tried anything else, for example "SDDE-222"?

**Comment by s0urcelab** [comment]
sry, it's my fault.
just test several keywords and coincidentally none of them get response.
but as your demo, ABP-123 is a correct name indeed, why does this happen?

**Comment by junzh0u** [comment]
@s0urcelab I can't say for sure. Maybe that one was taken down on dmm? I might look into it once I get the free time.
